development:
  adapter: postgresql
  encoding: unicode
  database: punterest_development
  pool: 5
  username: punterest
  password: punterest

test:
  adapter: postgresql
  encoding: unicode
  database: punterest_test
  pool: 5
  username: punterest
  password: punterest

production:
  adapter: postgresql
  encoding: unicode
  database: punterest_development
  pool: 5
  username: punterest
  password: punterest
