require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PunsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Pun. As you add validations to Pun, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PunsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all puns as @puns" do
      pun = Pun.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:puns)).to eq([pun])
    end
  end

  describe "GET show" do
    it "assigns the requested pun as @pun" do
      pun = Pun.create! valid_attributes
      get :show, {:id => pun.to_param}, valid_session
      expect(assigns(:pun)).to eq(pun)
    end
  end

  describe "GET new" do
    it "assigns a new pun as @pun" do
      get :new, {}, valid_session
      expect(assigns(:pun)).to be_a_new(Pun)
    end
  end

  describe "GET edit" do
    it "assigns the requested pun as @pun" do
      pun = Pun.create! valid_attributes
      get :edit, {:id => pun.to_param}, valid_session
      expect(assigns(:pun)).to eq(pun)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pun" do
        expect {
          post :create, {:pun => valid_attributes}, valid_session
        }.to change(Pun, :count).by(1)
      end

      it "assigns a newly created pun as @pun" do
        post :create, {:pun => valid_attributes}, valid_session
        expect(assigns(:pun)).to be_a(Pun)
        expect(assigns(:pun)).to be_persisted
      end

      it "redirects to the created pun" do
        post :create, {:pun => valid_attributes}, valid_session
        expect(response).to redirect_to(Pun.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pun as @pun" do
        post :create, {:pun => invalid_attributes}, valid_session
        expect(assigns(:pun)).to be_a_new(Pun)
      end

      it "re-renders the 'new' template" do
        post :create, {:pun => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pun" do
        pun = Pun.create! valid_attributes
        put :update, {:id => pun.to_param, :pun => new_attributes}, valid_session
        pun.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested pun as @pun" do
        pun = Pun.create! valid_attributes
        put :update, {:id => pun.to_param, :pun => valid_attributes}, valid_session
        expect(assigns(:pun)).to eq(pun)
      end

      it "redirects to the pun" do
        pun = Pun.create! valid_attributes
        put :update, {:id => pun.to_param, :pun => valid_attributes}, valid_session
        expect(response).to redirect_to(pun)
      end
    end

    describe "with invalid params" do
      it "assigns the pun as @pun" do
        pun = Pun.create! valid_attributes
        put :update, {:id => pun.to_param, :pun => invalid_attributes}, valid_session
        expect(assigns(:pun)).to eq(pun)
      end

      it "re-renders the 'edit' template" do
        pun = Pun.create! valid_attributes
        put :update, {:id => pun.to_param, :pun => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pun" do
      pun = Pun.create! valid_attributes
      expect {
        delete :destroy, {:id => pun.to_param}, valid_session
      }.to change(Pun, :count).by(-1)
    end

    it "redirects to the puns list" do
      pun = Pun.create! valid_attributes
      delete :destroy, {:id => pun.to_param}, valid_session
      expect(response).to redirect_to(puns_url)
    end
  end

end
